name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  reveal-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print S3_BUCKET_NAME
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          echo "S3_BUCKET_NAME: $S3_BUCKET_NAME"

      - name: Print UPLOAD_BUCKET_NAME
        env:
          UPLOAD_BUCKET_NAME: ${{ secrets.UPLOAD_BUCKET_NAME }}
        run: |
          echo "UPLOAD_BUCKET_NAME: $UPLOAD_BUCKET_NAME"
